language: csharp  
sudo: required  
dist: trusty  
env:  
  - CLI_VERSION=latest
mono: none
dotnet: 2.1.400
os:  
  - linux
branches:  
  only:
    - master
    - /.*/
before_script:
  - chmod +x ./build.sh
script:  
  - ./build.sh
deploy:
  provider: script
  script: chmod +x ./build.sh && ls && ./build.sh --target=Publish-AwsLambda
  skip_cleanup: true
  on:
    branch: master
    repo: CodeFiction/codefiction-tech-proxy
