language: csharp  
sudo: required  
dist: trusty  
env:  
  - CLI_VERSION=latest
mono: none
dotnet: 2.1.400
os:  
  - linux
branches:  
  only:
    - master
    - /.*/
before_script:
  - chmod +x ./build.sh
before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.9/terraform_0.11.9_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mkdir ~/bin
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"
script:  
  - ./build.sh
deploy:
  provider: script
  script: chmod +x ./build.sh && ls && ./build.sh --target=Publish-AwsLambda
  skip_cleanup: true
  on:
    branch: master
    repo: CodeFiction/codefiction-tech-proxy
